UPSTREAM: <carry>: Enable LLDP test downstream
openshift/kubernetes-nmstate pull request #478
Opened 2024-04-29 17:06 UTC by mkowalski

2024-04-29 17:06 UTC, mkowalski commented
/hold

2024-04-29 17:21 UTC, mkowalski commented
/test unit

2024-04-30 05:54 UTC, qinqon commented
/retest

Not related 
```
/hack/ssh-ci.shmaster-0 -- /usr/bin/nmcli c s : ssh: connect to host 128.31.20.106 port 22: Connection refused
       exit status 255
      {
          s: "./hack/ssh-ci.shmaster-0 -- /usr/bin/nmcli c s : ssh: connect to host 128.31.20.106 port 22: Connection refused\r\n exit status 255",
      }
```

2024-04-30 05:55 UTC, qinqon requested changes

2024-04-30 05:55 UTC, qinqon commented on hack/ocp-e2e-tests-handler.sh
>  with capture"
we should remove `with capture` too since is part of the test description.

2024-04-30 07:14 UTC, qinqon commented
/hold

Depends on https://github.com/openshift/kubernetes-nmstate/pull/479

2024-05-08 10:23 UTC, mkowalski commented
/hold cancel
/retest

2024-05-08 10:30 UTC, qinqon commented
/retest
```
  * could not run steps: step [release-inputs:initial] failed: failed to wait for importing imagestreamtags on ci-op-jsh6mb6h/stable-initial: failed to reimport the tag ci-op-jsh6mb6h/stable-initial:agent-installer-api-server: unable to import tag ci-op-jsh6mb6h/stable-initial:agent-installer-api-server with message dockerimage.image.openshift.io "quay.io/openshift/ci:ci-op-jsh6mb6h_stable-initial_agent-installer-api-server" not found on the image stream even after (6) imports: timed out waiting for the condition 
[36mINFO[0m[2024-05-08T10:29:24Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:creating_release_images' 
```

2024-05-08 11:20 UTC, mkowalski commented
/retest-required
```
{  failed to wait for importing imagestreamtags on ci-op-jsh6mb6h/stable-initial: timed out waiting for the condition}
```

2024-05-08 11:24 UTC, mkowalski commented
> /retest-required
> 
> ```
> {  failed to wait for importing imagestreamtags on ci-op-jsh6mb6h/stable-initial: timed out waiting for the condition}
> ```

It's PROW's issue, it crashed before our test suite even had a chance to run

2024-05-09 07:59 UTC, qinqon commented
/retest

2024-06-15 16:06 UTC, mkowalski commented
/retest

2024-06-17 17:13 UTC, mkowalski commented
/retest

2024-08-09 10:55 UTC, mkowalski commented
/retest

2024-08-09 19:22 UTC, mkowalski commented
/test e2e-handler-ovn-ipv4

OCP 4.18 fails, not a surprise

2024-08-12 07:13 UTC, mkowalski commented
/retest

2024-08-12 11:56 UTC, mkowalski commented
```
  > Enter [1m[AfterEach][0m when desiredState is updated with ovs-bridge with link aggregation port [38;5;243m- /go/src/github.com/openshift/kubernetes-nmstate/test/e2e/handler/simple_ovs_bridge_and_bond_test.go:129 @ 08/12/24 10:49:56.471[0m
Update error: admission webhook "nodenetworkconfigurationpolicies-update-validate.nmstate.io" denied the request: failed to admit NodeNetworkConfigurationPolicy test-policy: message: invalid policy operation: capture field cannot be modified. 
```

2024-11-29 11:56 UTC, mkowalski commented
/retest

2024-11-29 11:56 UTC, mkowalski commented
/remove-lifecycle stale

2024-11-29 16:08 UTC, mkowalski commented
/retest

Enormous amount of 

```
Update error: admission webhook "nodenetworkconfigurationpolicies-update-validate.nmstate.io" denied the request: failed to admit NodeNetworkConfigurationPolicy test-policy: message: invalid policy operation: capture field cannot be modified. 
```

Potentially a real failure. Let's see

2024-12-02 09:55 UTC, mkowalski commented
/test e2e-handler-sdn-ipv4

Trying without "with capture" to check if test "LLDP configuration with nmpolicy" will be skipped or not

2024-12-02 09:56 UTC, mkowalski commented
/test e2e-handler-ovn-ipv4

2024-12-03 14:40 UTC, mkowalski commented
/test e2e-handler-ovn-ipv4

2024-12-03 15:41 UTC, qinqon commented
/test e2e-handler-ovn-ipv4
not related 
```
[31mERRO[0m[2024-12-03T15:36:47Z] 
  * could not run steps: step e2e-handler-ovn-ipv4 failed: failed to acquire lease for "equinix-ocp-metal-quota-slice": status 502 Bad Gateway, status code 502 
  ```

2024-12-06 11:31 UTC, mkowalski commented
/test e2e-handler-ovn-ipv4

2024-12-17 08:55 UTC, phoracek commented
/retest

2025-01-09 09:31 UTC, mkowalski commented
/retest

2025-01-09 09:32 UTC, qinqon commented
/lgtm

2025-01-09 13:08 UTC, qinqon commented
/override security

2025-01-09 13:19 UTC, qinqon commented
/override ci/prow/security

2025-01-09 16:34 UTC, qinqon commented
/retest

2025-01-10 10:33 UTC, mkowalski commented
/retest-required

2025-01-14 21:59 UTC, merged